### ISSUE TITLE
図書館事業や図書館業務の基礎知識の参考リンク

### ISSUE THREAD

**Issue by masuda220** [system-sekkei/library#3]
# 業務
- [図書館司書の10個の業務](https://joboole.jp/articles/964396)
- [司書になるには・仕事内容と本音・全国の求人｜スタンバイ](https://jp.stanby.com/contents/detail/shisho)

# 遅延罰則

## 大阪市

市の条例で規定。

- [図書館資料利用規程 - 大阪市立図書館](https://www.oml.city.osaka.lg.jp//?page_id=441)
    - 13条 

# 公立図書館の事業

## 役割・目的

- [図書館法 | e-Gov法令検索](https://elaws.e-gov.go.jp/document?lawid=325AC0000000118)

## 予算（コスト構造）

- [図書館経営：文部科学省](https://www.mext.go.jp/a_menu/shougai/tosho/giron/05080301/001/004.htm)

## 貸出統計・蔵書統計

- [統計 - 大阪市立図書館](https://www.oml.city.osaka.lg.jp//?page_id=447)
- [大阪市立図書館年報 - 大阪市立図書館](https://www.oml.city.osaka.lg.jp/?page_id=421)

## 司書インタビューや生の声

- [丸善雄松堂の図書館支援サービス｜図書館で働きたい方へ｜全国で活躍するスタッフの声](https://library.maruzen.co.jp/work/voice.html)
- [司書のやりがい・楽しさ・魅力 | 司書の仕事・なり方・年収・資格を解説 | キャリアガーデン](https://careergarden.jp/shisho/yarigai/)
- [とある図書館司書見習いのブログ](https://kurobutalibrarian.hatenablog.com/)
    - 図書館員の方のブログ。窓口や予約業務などの様子がわかる。
        - [図書館がサービス業と感じる瞬間。 - とある図書館司書見習いのブログ](https://kurobutalibrarian.hatenablog.com/entry/2019/11/10/181409)
        - [何かと急かす利用者さん〜とある図書館員の日記〜 - とある図書館司書見習いのブログ](https://kurobutalibrarian.hatenablog.com/entry/2019/10/22/083421)
- [【通信教育部】大人が今学びたい司書講座「もし大人になった今、本について学んだとしたら」 - YouTube](https://www.youtube.com/watch?v=VpYJzlhNYAc&t=253s)
- [発見！こうべおしごと調査隊－図書館司書のおしごと - YouTube](https://www.youtube.com/watch?v=_2OId93Z4MM&t=3s)
- [【岩手県 久慈市】久慈市立図書館（YOMUNOSU）に行ってみた！ - YouTube](https://www.youtube.com/watch?v=ni9zP6VRKpo&t=1722s)
- [貸出冊数 - 図書館ごくらく日記](https://katsura-yokoyama.hatenablog.com/entry/2018/04/14/173353)

## 参考書籍

- [夜明けの図書館 ： 1 (ジュールコミックス) | 埜納 タオ | 女性マンガ | Kindleストア | Amazon](https://www.amazon.co.jp/%E5%A4%9C%E6%98%8E%E3%81%91%E3%81%AE%E5%9B%B3%E6%9B%B8%E9%A4%A8-%EF%BC%9A-%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%82%B3%E3%83%9F%E3%83%83%E3%82%AF%E3%82%B9-%E5%9F%9C%E7%B4%8D-%E3%82%BF%E3%82%AA-ebook/dp/B009DYOJ7O)
    - 司書レファレンス業がテーマのマンガ
- [Amazon.co.jp: レファレンスと図書館 ある図書館司書の日記 eBook : 大串 夏身: 本](https://www.amazon.co.jp/gp/product/B081V4TW2W/ref=ppx_yo_dt_b_d_asin_title_o01?ie=UTF8&psc=1)
    - 実際のレファレンスのやり取り記録や、資料の探し方についてなど。
- [図書館概論 (JLA図書館情報学テキストシリーズ3) | 昇, 塩見 |本 | 通販 | Amazon](https://www.amazon.co.jp/gp/product/4820418130/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1)
- [中小都市における公共図書館の運営―中小公共図書館運営基準委員会報告 | 日本図書館協会 |本 | 通販 | Amazon](https://www.amazon.co.jp/%E4%B8%AD%E5%B0%8F%E9%83%BD%E5%B8%82%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%85%AC%E5%85%B1%E5%9B%B3%E6%9B%B8%E9%A4%A8%E3%81%AE%E9%81%8B%E5%96%B6%E2%80%95%E4%B8%AD%E5%B0%8F%E5%85%AC%E5%85%B1%E5%9B%B3%E6%9B%B8%E9%A4%A8%E9%81%8B%E5%96%B6%E5%9F%BA%E6%BA%96%E5%A7%94%E5%93%A1%E4%BC%9A%E5%A0%B1%E5%91%8A-%E6%97%A5%E6%9C%AC%E5%9B%B3%E6%9B%B8%E9%A4%A8%E5%8D%94%E4%BC%9A/dp/4820473018/ref=cm_cr_arp_d_product_top?ie=UTF8)
- [図書館のしごと ―よりよい利用をサポートするために   独立行政法人国際交流基金関西国際センター](https://www.amazon.co.jp/dp/4902666332/ref=cm_sw_r_tw_dp_YVHYVC915S03ER191YPP)
-  [市民の図書館](https://www.amazon.co.jp/dp/4820476009/ref=cm_sw_em_r_mt_dp_2K5T29KAF3T7XCG3R6NY)
- [図書館と法: 図書館の諸問題への法的アプローチ (JLA図書館実践シリーズ 12) 鑓水 三千男](https://www.amazon.co.jp/dp/482042100X/ref=cm_sw_r_tw_dp_F6BBBDYQNR329114VQYH)

**Comment by SAMMY7th** [comment]
リンクをいくつか追加しました。
