### ISSUE TITLE
所蔵品の貸出可否を提示する ユースケースの妥当性

### ISSUE THREAD

**Issue by stgctkm** [system-sekkei/library#44]
貸出を登録する際には、本（所蔵品）の現物を持って窓口に来ているので、
所蔵品の貸出可否を判定するユースケースはないかと思いました。

窓口、もしくはWebで、所蔵品目から保有する全ての所蔵品の貸出可否を問い合わせて、
「予約もしくは貸出」という業務の方がありそうに思います。

https://github.com/system-sekkei/library/blob/1836f045737f26749aad46ed24cbc06a5dbd7631/src/main/java/library/application/scenario/loan/LoanScenario.java#L72-L81

![image](https://github.com/system-sekkei/library/assets/3186646/2a361ffb-621e-4267-8543-87ecf29159cd)

**Comment by SAMMY7th** [comment]
予約されているけれどもまだ取り置かれていない所蔵品を持っていくケースや、その他特殊な事情で貸し出せないパターンもありそうなので、このチェックは必要だと思います。

https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1044320305

**Comment by stgctkm** [comment]
貸出禁止の本ですね。
`ItemLoanability`のその他を明示的な区分として定義した方がいいかもしれませんね。

ありがとうございました。クローズします
