### ISSUE TITLE
図書館 延滞問題についての参考リンク

### ISSUE THREAD

**Issue by SAMMY7th** [system-sekkei/library#7]
# 図書館 延滞問題

## 延滞の状況の数値データが具体的な資料

- [「本が帰ってこない」悩む公立図書館: 日本経済新聞](https://www.nikkei.com/article/DGXMZO26523040V00C18A2CC0000/)
	- 10年以上返却されなかった本が1万9千冊。総額役2500万円。
	- 15年度までの4年間で4502冊。16年度に回収できたのが19冊。
	- 16年度に督促はがきを約1万7千枚送り、約84万円がかかった。過去5年間では500万。
- [大学図書館における督促について](https://www.jstage.jst.go.jp/article/jcul/33/0/33_857/_pdf/-char/ja)
	- 24%が未返却
-  [貸出規則 と延滞防止](https://www.jstage.jst.go.jp/article/igakutoshokan1954/12/2/12_2_93/_pdf)
	-  昭和38年の資料
	-  貸出の30%が未返却
-   [図書館資料延滞者を減らす取り組みについて（案）](https://www.nabari-library.jp/doc/tosyokankyougikai2015-4.pdf)
	-   名張市の資料
	-   督促者数一覧あり
	-   貸出人数5,512人で延滞者が437人。(7.9%)。貸出冊数25,356冊のうち延滞が1,503冊 (5.9%)
	-   3年以上回収不能な資料は除籍。(平成24年度 30点、25年度 24点)

## 軽度な延滞の対応方法や、延滞の予防的な取り組みが具体的な資料

- [督促・お知らせメールサービス :: 長崎大学附属図書館](http://www.lb.nagasaki-u.ac.jp/use/webserv/mails/)
	- 督促メールサービス
		- 毎週月曜日13時の時点で延滞されている場合メールでお知らせ
	- 返却日事前通知
		- 返却期限2日前にメールでお知らせ
- [米原市立図書館の資料の返却督促および貸出制限基準](https://www.lics-saas.nexs-service.jp/maibara/img/kashidashiseigen.pdf)
	- 返却期日から30日以上経過で督促
	- 督促をうけながら返却期日から60日以上経過する遅滞者に対して督促状を送付
		- 電話、電子メール、はがき
	- 遅滞者不在時に、書名・著者名などは伝えない
	- 郵便の督促時、書名・著者名は掲載しない
		- 遅滞者の読書の秘密を守るため
	- 遅滞者に対しては、資料が返却されるまでの期間は貸出停止・予約受付停止
-   [図書館資料延滞者を減らす取り組みについて（案）](https://www.nabari-library.jp/doc/tosyokankyougikai2015-4.pdf)
	-   督促
		-   返却期日が過ぎた時点で電話・窓口で督促、14日以上未返却で督促はがきを送付
		-   2ヶ月以上の長期延滞で封書を送付
- [図書資料延滞者に対する貸出し制限等について](https://www.city.kasugai.lg.jp/_res/projects/default_project/_page_/001/008/092/kashidasiseigenn.pdf)
	- 毎月2回、直前2週間前の返却期限までに資料未返却の利用者に対してハガキで督促
	- 返却期限が過ぎた時点でまず電話で督促
	- メールアドレスが登録してある利用者について、返却期限から２週間経過した時点で督促メールを送信
		- 年4回、前年度以前3年分も併せて送信
	- 返却期限から30日経過で貸出・予約停止
		- 罰則開始の2週間前にハガキ・メールで通知

## 重度な延滞についての統計や取り組みの資料

- [図書館資料の督促や延滞や時効などに関する資料 | レファレンス協同データベース](https://crd.ndl.go.jp/reference/modules/d3ndlcrdentry/index.php?page=man_view&id=2000016001)
- [「図書館の自由」と図書館ネットワーク －延滞督促方法をめぐって－](https://www2.okiu.ac.jp/yamaguchi/entai.pdf)
-  [市民の図書館](https://www.amazon.co.jp/dp/4820476009/ref=cm_sw_em_r_mt_dp_2K5T29KAF3T7XCG3R6NY)
	-  p52 延滞・亡失
		-  『利用者はなかなか期限内に本を返さず延滞が貸出しの10%、多くなると20%にも達することがある』
		-  督促を促す、一定期間の貸出停止処分とするか罰を課さないことにするのがよく、延滞料の徴収は労多くして効少ないとある。
- [図書館と法: 図書館の諸問題への法的アプローチ (JLA図書館実践シリーズ 12) 鑓水 三千男](https://www.amazon.co.jp/dp/482042100X/ref=cm_sw_r_tw_dp_F6BBBDYQNR329114VQYH)
	- p196 Q2 図書館資料の延滞について、法的に妥当な処置方法を教えてください
		1. 督促
			- 電話、電子メール、郵便
		2. 訴訟の提起
			- 督促を行ってもなお返却がない場合
		3. 貸出制限
			- 一定の期間貸出を禁止・制限する
		4. 延滞料の徴収
			- 費用対効果の点を考え、現在ではほとんどない

**Comment by masuda220** [comment]
@SAMMY7th 
ありがとうございます。
よい情報がいろいろ集まってきましたね。

この資料を次の観点からざっくりと分類してみてもらえますか？

①延滞の状況の数値データが具体的
②軽度な延滞の対応方法や、延滞の予防的な取り組みが具体的
③重度な延滞についての統計や取り組み

基本的には、①を理解しつつ、②をアプリケーションとして何をどこまで実装するか、という方向で検討しましょう。
③は背景知識として知っていたほうがよい情報です。しかし③は、アプリケーションの基本仕様にはあまり関係しません。

**Comment by SAMMY7th** [comment]
@masuda220 
ざっくりと分類してみました。
